### ISSUE TITLE
Rewrite capture module in Swift

### ISSUE THREAD

**Issue by benjohnde** [zxingify/zxingify-objc#351]

**Comment by neacao** [comment]
@benjohnde , i can handle this but that means you want to split ZXCapture.* outside ZXingObjC ? If not, how about the rest in `client` folder ?

**Comment by benjohnde** [comment]
Ah, you refer to #422? Yeah, I want to move everything from `client` into another project.

**Comment by neacao** [comment]
that shall be long-term working, so should ZXCapture.* be moved to example projects first, be a part of BarcodeScanner ?

**Comment by benjohnde** [comment]
Of course, I want the tests to be also decoupled from the current project (to reduce cloning bloat a lot).

The left hand side: Example requires client requires core. This could be done right now. I will start with the decoupling right after I finished porting the outstanding commits.

The right hand side should be implemented later on. I just had in mind to create another example written in Swift and let the current one hang around. Swift API should be completely rethought to provide some Swifty <3 experience.

**Comment by benjohnde** [comment]
But that's important: the core should remain in ObjC (at least until Swift 5 is here) and most of the code should be similar as it was derived straight from zxing/zxing. This makes it much easier to identify bugs and upstream those to zxing/zxing or to downstream new enhancements/commits.

**Comment by benjohnde** [comment]
Hence, the idea of a Swift API in form of a shim.

**Comment by neacao** [comment]
To make things easier, i think it's good to start #347 when you'r porting commits from zxing, so we could avoid revert source code of `client` if there was any changed from zxing repo

**Comment by benjohnde** [comment]
Yeap, I will dig into some Swift example tomorrow.

**Comment by benjohnde** [comment]
Okay, perfect 🎉 ! :)

**Comment by benjohnde** [comment]
Won't be done in near future
