### ISSUE TITLE
example application not scanning any barcode - iPhone X, iOS 12.1, Objective-c

### ISSUE THREAD

**Issue by jseter** [zxingify/zxingify-objc#453]
In a previous version I was able to get it to scan some barcodes but only when in landscape orientation. With version 3.6.1 it does not appear to adjust to landscape, remaining the width of portrait while in landscape orientation.  I could not find any barcode that it detected in any orientation.

**Comment by jseter** [comment]
Tested swift example.  It also does not recognize any barcodes.

**Comment by benjohnde** [comment]
I am going to test that out later tomorrow.

**Comment by benjohnde** [comment]
Does the objective-c version work for you?

**Comment by benjohnde** [comment]
@neacao maybe you could have a look as well :)

**Comment by neacao** [comment]
Have checked already, can you provide the barcode that could not decoded @jseter ?

**Comment by jseter** [comment]
@neacao If you was able to scan any barcode with the specific environment posted then you are already having more success than me.  I tried just regular UPC-A off several available products as well as some QR codes and GS1-128.  I'll have to retest.  I know the core library is functional as I was able to get it working for my needs writing my own image capture code so the problem seems limited to the ZXCapture code.

**Comment by jseter** [comment]
![landscape-screenshot](https://user-images.githubusercontent.com/20651459/50647746-5da99400-0f47-11e9-9829-60626ab50187.png)
![portrait-screenshot](https://user-images.githubusercontent.com/20651459/50647747-5da99400-0f47-11e9-8265-7b61fdcefa09.png)
![test barcode 1](https://user-images.githubusercontent.com/20651459/50647748-5da99400-0f47-11e9-8fea-fc6afd40fa16.png)

**Comment by rizoto** [comment]
the delegate is missing in the example (ObjC) 
you can add this line to "- (void)viewDidLoad"

_**self.capture.delegate = self;**_

I had an issue with scanning in the landscape orientation

my fix in ViewController.m

//  CGAffineTransform transform = CGAffineTransformMakeRotation((CGFloat) (captureRotation / 180 * M_PI));
//  [self.capture setTransform:transform];
    [self.capture setOrientation:(AVCaptureVideoOrientation)orientation];

+add to ZXCapture.m + h
- (void)setOrientation:(AVCaptureVideoOrientation)orientation {
    AVCaptureConnection *connection = _layer.connection;
    if ([connection isVideoOrientationSupported]) {
        [connection setVideoOrientation:orientation];
    }
}

**Comment by kalyanpkumar** [comment]
I too have the same issue on iPhone X with 12.1.x and I am trying to scan PDF417 type codes. Driving Licence barcodes. So may I please know if this issue is fixed?

**Comment by zrx89757** [comment]
same issue with me. The swift example performance good on my iPhone6, iPhone6s, both 12.x iOS version. But quite badly on my iPhone11, 13.x iOS version.  I test some barcode like UPS, DHL tracking number, iPhone 6 can correctly scan they, but iPhone11 can't

**Comment by thangcntt0290** [comment]
Same issue with me.
i using -(void)captureOutput:(AVCaptureOutput *)captureOutput didOutputMetadataObjects:(NSArray *)metadataObjects fromConnection:(AVCaptureConnection *)connection
And i scan PDF417 barcode, it's work with some barcode but not work with attached photo
P/s: i have android code can detected barcode on attached photo.
Please help me !!!

![7](https://user-images.githubusercontent.com/58938511/70902620-d0fcc680-202f-11ea-9052-4da818d0217a.jpg)

**Comment by tobinP** [comment]
For anyone still having trouble with this, add capture luminance to get a better idea of where to position the barcode.  The default gray box is inaccurate.

Add this in the `viewDidLoad` of the main view controller:

```
[self.capture setLuminance: TRUE];
[self.capture.luminance setFrame: CGRectMake(150, 30, 100, 100)];
[self.view.layer addSublayer: self.capture.luminance];
```

**Comment by benjohnde** [comment]
Unfortunately, I can no longer provide support for this codebase, the topic will be closed. I recommend to take a look at https://github.com/zxing-cpp/zxing-cpp created and maintained by the very ambitious @axxel!
