### ISSUE TITLE
How can i generate data matrix with ECC 200 symbol encoded in the syntax of ISO/IEC 15434 and using the semantics of ISO/IEC 15418

### ISSUE THREAD

**Issue by devkaranmakvana** [zxingify/zxingify-objc#465]
Thanks for the amazing library. 

I have used your library for 2D Data Matrix Encoding, This is the string we are encoding. 
[)>~d03005~d02980040614141ABC123456~d030~d004

// code for generating Data matrix image

        let error : Error? = nil
        
        let hints = ZXEncodeHints() as ZXEncodeHints
        hints.encoding = 1
        hints.dataMatrixShape = ZXDataMatrixSymbolShapeHintForceSquare
        hints.margin = 0.02
        
        let writer = ZXMultiFormatWriter()
        let matrixCodeString = "[)>~d03005~d02980040614141ABC123456~d030~d004"
        
        let result = try? writer.encode(matrixCodeString, format: kBarcodeFormatDataMatrix, width: 120, height: 120, hints: hints)
        
We got result image but it's not in standard ECC 200 data matrix format. Could you please help us fix this?

Thanks,
Dev

**Comment by benjohnde** [comment]
Unfortunately, I can no longer provide support for this codebase, the topic will be closed. I recommend to take a look at https://github.com/zxing-cpp/zxing-cpp created and maintained by the very ambitious @axxel!
