### ISSUE TITLE
Cannot scan PDF417 type barcode is not scanning on iPhone X with iOS 12.1.2

### ISSUE THREAD

**Issue by kalyanpkumar** [zxingify/zxingify-objc#466]
I updated my device iPhone X to iOS 12.1.2 and my app is no more scanning the PDF417 codes. (example back of Driving Licence codes). It used to work fine earlier the update.

**Comment by benjohnde** [comment]
Unfortunately, I can no longer provide support for this codebase, the topic will be closed. I recommend to take a look at https://github.com/zxing-cpp/zxing-cpp created and maintained by the very ambitious @axxel!
