### ISSUE TITLE
Codabar scanning problem

### ISSUE THREAD

**Issue by DavidLari** [zxingify/zxingify-objc#467]
## Environment: 

Running iOS 12.1.3 on an iPhone XS Max, using ZXingObj latest version (3.6.4) installed via cocoapods, and running the example app, built on XCode 10.1 (10B61).

## Expected Result:

When using the example app, I should be able to scan Codabar codes consistently and by placing the barcode in the center of the screen, as defined by the semitransparent square on the screen.

## Actual Result:

I am getting inconsistent results scanning Codabar codes. It seems that the rectangle that is actually being scanned is just below the scan box that is drawn on the screen.

**Comment by benjohnde** [comment]
Unfortunately, I can no longer provide support for this codebase, the topic will be closed. I recommend to take a look at https://github.com/zxing-cpp/zxing-cpp created and maintained by the very ambitious @axxel!
