### ISSUE TITLE
move scanRect from the center of the screen  I

### ISSUE THREAD

**Issue by takahashi5110** [zxingify/zxingify-objc#468]
If the position of scanRect is shifted from the center of the screen, the reading range will be shifted, but what should I do?

1. Using the iPad
2. In BarcodeScannerSwift Main.storyboard, shift Align center Y of Scan View up -100
3. Set the Scan View Width: 600 Height: 400
4. When executing the application, it can not read in the upper half of Scan View, lower half and Scan View About 100 pixels out of frame? Can read

**Comment by eamonn-alphin** [comment]
I'm having issues with this too. I don't understand how to adjust the scanrect in portrait. I want it to be 10 points high and the full width, but even with the preview layer taking up 100% of the screen, the actual rectangle of interest is below where I have defined it. The only time it's 100% accurate is when the scanrect is at 0,0 and 100% width.

**Comment by benjohnde** [comment]
Unfortunately, I can no longer provide support for this codebase, the topic will be closed. I recommend to take a look at https://github.com/zxing-cpp/zxing-cpp created and maintained by the very ambitious @axxel!
