### ISSUE TITLE
unable to read QR code

### ISSUE THREAD

**Issue by 810152690** [zxingify/zxingify-objc#470]
Hi, i have image that unable to read QR.
![image](https://user-images.githubusercontent.com/1946356/53459690-be4fdb80-3a75-11e9-8f4f-046114ee275d.png)
I found
```
- (ZXDetectorResult *)detect:(ZXDecodeHints *)hints error:(NSError **)error {
  self.resultPointCallback = hints == nil ? nil : hints.resultPointCallback;

  ZXQRCodeFinderPatternFinder *finder = [[ZXQRCodeFinderPatternFinder alloc] initWithImage:self.image resultPointCallback:self.resultPointCallback];
  ZXQRCodeFinderPatternInfo *info = [finder find:hints error:error];
  if (!info) {
    return nil;
  }

  return [self processFinderPatternInfo:info error:error];
}
```
info always is nil. So i can't read QRCode from image.
I don't know the reason.

**Comment by benjohnde** [comment]
Unfortunately, I can no longer provide support for this codebase, the topic will be closed. I recommend to take a look at https://github.com/zxing-cpp/zxing-cpp created and maintained by the very ambitious @axxel!
