### ISSUE TITLE
DataMatrix barcode not recognized

### ISSUE THREAD

**Issue by skogsbaer** [zxingify/zxingify-objc#474]
I'm trying to scan DataMatrix barcodes under iOS with ZXing. Some barcodes are recognized but many are not. Here is a picture for which ZXing fails to recognize the barcode on my iPhone 8:

![datamatrix](https://user-images.githubusercontent.com/567524/57140785-e3840180-6db8-11e9-9186-3bb00c792edd.jpg)

Here is the code that invokes ZXing on a given `CGImageRef`:

```objective-c
- (BarcodeResult *)findBarcode:(CGImageRef)img
{
    ZXLuminanceSource *source = [[ZXCGImageLuminanceSource alloc] initWithCGImage:img];
    ZXBinaryBitmap *bitmap = [ZXBinaryBitmap binaryBitmapWithBinarizer:[ZXHybridBinarizer binarizerWithSource:source]];
    NSError *error = nil;
    ZXMultiFormatReader *reader = [ZXMultiFormatReader reader];
    ZXResult *result = [reader decode:bitmap
                                hints:self.hints
                                error:&error];
    if (result) {
        NSString *contents = result.text;
        ZXBarcodeFormat format = result.barcodeFormat;
        NSString *kindString = barcodeFormatToString(format);
        return [[BarcodeResult alloc] initWithKind:kindString text:contents];
    } else {
        return nil;
    }

}
```

The hints are configured as follows:

```objective-c
    ZXDecodeHints *hints = [ZXDecodeHints hints];
    hints.tryHarder = YES;
    [hints addPossibleFormat:kBarcodeFormatDataMatrix];
    [hints setEncoding:NSISOLatin1StringEncoding]; // I know that the code is latin1 encoded
```

Any suggestions how to get barcode scanning to work for such DataMatrix codes?

**Comment by skogsbaer** [comment]
any progress on this ticket?

**Comment by SNThunderbolt** [comment]
> any progress on this ticket?

Could you find any workarounds?
I have the exact same issue

**Comment by akshardarji** [comment]
@skogsbaer Not sure, however, you can try by downsize the resolution of the image and pass that image in method `findBarcode`.

**Comment by benjohnde** [comment]
I am going to look into that issue as I am bringing some fixes to the DataMatrix reader. Hopefully that fixes your issue. I cannot give extended support for that port besides bringing the main functionality back as good as I can.

**Comment by benjohnde** [comment]
Unfortunately, I can no longer provide support for this codebase, the topic will be closed. I recommend to take a look at https://github.com/zxing-cpp/zxing-cpp created and maintained by the very ambitious @axxel!
