### ISSUE TITLE
Is there a way to remove huge white borders around the generated  data matrix?

### ISSUE THREAD

**Issue by orkhanalizade** [zxingify/zxingify-objc#479]
I'm generating my data matrix via:

    hints.dataMatrixShape = ZXDataMatrixSymbolShapeHintForceSquare
    hints.margin = NSNumber(0.0)

    let result = try writer.encode(xml, format: kBarcodeFormatDataMatrix, width: Int32(barcodeImageView.frame.width - 22.0), height: Int32(barcodeImageView.frame.height - 22.0), hints: hints)
            
            if let imageRef = ZXImage.init(matrix: result) {
                if let image = imageRef.cgimage {
                    let image = UIImage.init(cgImage: image)
                    barcodeImageView.image = image
                    barcodeImageView.contentMode = .scaleToFill
                }
            }

and in the result I get this:

[Image](https://imgur.com/7Pkq0Fw)

Can someone help me to remove that white border from it?

**Comment by benjohnde** [comment]
Unfortunately, I can no longer provide support for this codebase, the topic will be closed. I recommend to take a look at https://github.com/zxing-cpp/zxing-cpp created and maintained by the very ambitious @axxel!
