### ISSUE TITLE
How to have text below barcode

### ISSUE THREAD

**Issue by mpogra** [zxingify/zxingify-objc#481]
Hello,
Thanks for the great work and we really like it. We got a strange requirement to show text below the barcode like this image -

![barcode-5c81647c46e0fb00011365f0](https://user-images.githubusercontent.com/10540903/61574076-f31d0780-aad6-11e9-9b8b-5a284f027898.jpg)

 Pleease, advise how we can do that. 

Thanks.

**Comment by benjohnde** [comment]
Unfortunately, I can no longer provide support for this codebase, the topic will be closed. I recommend to take a look at https://github.com/zxing-cpp/zxing-cpp created and maintained by the very ambitious @axxel!
