### ISSUE TITLE
Some Blurred picture(the black block has white dot) can't scan 

### ISSUE THREAD

**Issue by anhuijhy** [zxingify/zxingify-objc#483]
I change ZXHybridBinarizer to ZXGlobalHistogramBinarizer  .If the picture is not so blur it can scan, but some not.The pic as below, so someone has solve method?

<img width="364" alt="屏幕快照 2019-08-01 下午11 56 54" src="https://user-images.githubusercontent.com/6006752/62308553-18871980-b4b8-11e9-94f5-304e20fbeba7.png">

the pic change  ZXHybridBinarizer to ZXGlobalHistogramBinarizer can scan
<img width="379" alt="屏幕快照 2019-08-01 下午11 59 32" src="https://user-images.githubusercontent.com/6006752/62308695-7156b200-b4b8-11e9-849f-3da813a77ba9.png">

**Comment by Macarons-arch** [comment]
![image](https://user-images.githubusercontent.com/81785896/150947180-2ad6bda1-c399-4b17-a757-30bb99542b38.png)
like this

**Comment by benjohnde** [comment]
Unfortunately, I can no longer provide support for this codebase, the topic will be closed. I recommend to take a look at https://github.com/zxing-cpp/zxing-cpp created and maintained by the very ambitious @axxel!
