### ISSUE TITLE
interesting issue for capture rotation

### ISSUE THREAD

**Issue by anhuijhy** [zxingify/zxingify-objc#484]
for the  fuzzy QR code image ,if I tilt the phone can scan normal .So I change the code as below will be ok(change UIInterfaceOrientationPortrait scanRectRotation to 110)。Could some one can explain this?
  //====
    switch (orientation) {
        case UIInterfaceOrientationPortrait:
            captureRotation = 0;
            scanRectRotation = 110;
            break;
     //=====
the image is 
![lADPDgQ9q32W4hrNAvTNA_A_1008_756 jpg_620x10000q90g](https://user-images.githubusercontent.com/6006752/62420944-0e8a3400-b6cd-11e9-82dc-0d083a87f8e7.jpg)

**Comment by benjohnde** [comment]
Unfortunately, I can no longer provide support for this codebase, the topic will be closed. I recommend to take a look at https://github.com/zxing-cpp/zxing-cpp created and maintained by the very ambitious @axxel!
