### ISSUE TITLE
GS1 Data Bar (RSS) badly scanned on examples

### ISSUE THREAD

**Issue by IVANKRUPSKI** [zxingify/zxingify-objc#485]
Why GS1 Data Bar (RSS) so badly scanned on the examples?

All other formats are caught at once, while this one really badly.

**Comment by benjohnde** [comment]
Unfortunately, I can no longer provide support for this codebase, the topic will be closed. I recommend to take a look at https://github.com/zxing-cpp/zxing-cpp created and maintained by the very ambitious @axxel!
