### ISSUE TITLE
Please help document how to `scanRect` work?

### ISSUE THREAD

**Issue by phuhk** [zxingify/zxingify-objc#486]
Hi all, thanks for reading my issue.
I'm just follow the example project about how to set `scanRect`, but I have found issue for this guide when apply with iPhone has notch or iPad, `scanRect` seem not work properly. Can someone please help me for the right way for set `scanRect`. Please and thanks.

**Comment by DavidLari** [comment]
I have the same problem. I don't know the solution.

**Comment by skyofdwarf** [comment]
⚠️ Bad English

Recently, I dug the same issue with the example for `scanRect`, and fixed scanRect calculations with some assumptions.

Assumes the below.

ZXCapture's layer does not show the full width of the video on portrait orientation.

* the `height` of video equals the `height` of layer of ZXCapture(layer.frame.height)
* the `width` of video equals or larger than the `width` of layer of ZXCapture(layer.frame.width)

And assumes the below.

ZXCapture's layer does not show the full height of the video on landscape orientation.

* the `height` of video equals the `width` of layer of ZXCapture(layer.frame.`width`)
* the `width` of video equals or larger than the `height` of layer of ZXCapture(layer.frame.height)

I wish my fix to be helped.

```swift
extension ZXCapture {
    func applyRectOfInterest(_ interest: CGRect?, orientation: UIInterfaceOrientation) {
        guard var interest = interest,
            ...
            else {
                return
        }

        let videoHeight = ...
        let videoWidth = ...

        var interest = frame

        if orientation.isPortrait {
            let heightRatio = layer.frame.height / videoWidth
            let fixedWidth = videoHeight * heightRatio

            let xPadding = 0
            if fixedWidth > layer.frame.width {
                xPadding = (fixedWidth - layer.frame.width) / 2
            }

            let fixedInterestWidth = interest.width / heightRatio
            let fixedInterestHeight = interest.height / heightRatio

            let interestXRatio = (interest.origin.x + xPadding) / fixedWidth
            let fixedX = videoHeight * interestXRatio

            let interestYRatio = interest.origin.y / layer.frame.height
            let fixedY = videoWidth * interestYRatio

            scanRect = CGRect(
                x: fixedY,
                y: fixedX,
                width: fixedInterestHeight,
                height: fixedInterestWidth)

        }
        else {
            let widthRatio = layer.frame.width / videoWidth
            let fixedHeight = videoHeight * widthRatio

            let yPadding = 0
            if fixedHeight > layer.frame.height {
                yPadding = (fixedHeight - layer.frame.height) / 2
            }

            let fixedInterestWidth = interest.width / widthRatio
            let fixedInterestHeight = interest.height / widthRatio

            let interestXRatio = interest.origin.x / layer.frame.width
            let fixedX = videoWidth * interestXRatio

            let interestYRatio = (interest.origin.y + yPadding) / fixedHeight
            let fixedY = videoHeight * interestYRatio

            scanRect = CGRect(
                x: fixedX,
                y: fixedY,
                width: fixedInterestWidth,
                height: fixedInterestHeight)
        }
    }
}
```

**Comment by eamonn-alphin** [comment]
I'm having the same trouble, I can't see to resize the scanRect in a way that makes sense. To make it as wide as the screen, you have to set it's height to the screenwidth * 2, for example.

**Comment by benjohnde** [comment]
Unfortunately, I can no longer provide support for this codebase, the topic will be closed. I recommend to take a look at https://github.com/zxing-cpp/zxing-cpp created and maintained by the very ambitious @axxel!
