### ISSUE TITLE
Issue when enabling Undefined behaviour Sanitizer check

### ISSUE THREAD

**Issue by HanumanKachwa** [zxingify/zxingify-objc#492]
Left shift of 1 by 31 places cannot be represented in type 'int
`- (void)appendBit:(BOOL)bit {
  [self ensureCapacity:self.size + 1];
  if (bit) {
    self.bits[self.size / 32] |= 1 << (self.size & 0x1F);
  }
  self.size++;
}
`

`    self.bits[self.size / 32] |= 1 << (self.size & 0x1F);
`

**Comment by benjohnde** [comment]
Unfortunately, I can no longer provide support for this codebase, the topic will be closed. I recommend to take a look at https://github.com/zxing-cpp/zxing-cpp created and maintained by the very ambitious @axxel!
