### ISSUE TITLE
Crash at CFRelease in ZXCapture when rotating

### ISSUE THREAD

**Issue by Halfpint-Code** [zxingify/zxingify-objc#496]
CGImageRef rotatedImage = CGBitmapContextCreateImage(context);
CFRelease(context);

When I rotate the device, I'm getting an EXC_BREAKPOINT exception at the CFRelease in createRotatedImage in the ZXCapture file. Is anyone else getting this in either the sample or in their own projects? Is there a work around?

**Comment by iMostfa** [comment]
same problem, any help?

**Comment by benjohnde** [comment]
Unfortunately, I can no longer provide support for this codebase, the topic will be closed. I recommend to take a look at https://github.com/zxing-cpp/zxing-cpp created and maintained by the very ambitious @axxel!

Hopefully this is already fixed with the overhaul of the sample app, cf. #527.
