### ISSUE TITLE
Specify exact dimensions of Data Matrix

### ISSUE THREAD

**Issue by dvertovsek** [zxingify/zxingify-objc#497]
I have a specific requirement, i was wondering if its possible to build a **data matrix** that is:

- 64x64mm
- 14x14 squares composing the data matrix

the **string** encoded that would be encoded would be 8 characters long

Would something like that be possible and what would be the closest i could get to it ?

Our client has a reader that can read only those kind of data matrices, so im wondering if its possible.

Thanks in advance

**Comment by benjohnde** [comment]
Please consult the official repo (https://github.com/zxing/zxing) for that type of question. We are only collecting issues regarding the port.
