### ISSUE TITLE
Not able to scan the datamatrix barcodes

### ISSUE THREAD

**Issue by kalyanpkumar** [zxingify/zxingify-objc#498]
I am working on an application to scan the DataMatrix barcodes on iOS / Android with the Zxing library. But having issues with library not able to scan the DataMatrix barcodes. That barcode is just an URL. I didn't configure any specific hints.. This used to work with QR-Codes without any issues but not with DataMatrix codes.

1 out of 10 Datamatrix codes are successfully scanned but not others. are there any settings that I need to look out for.

**Comment by dennishahn** [comment]
I am having the same problem with scanning data matrix codes in the example `BarcodeScannerSwift`. If the data matrix is just one field it is most of the time possible to scan it. If it's bigger like 4x4 it is not scanning. Is there any way to change the configuration maybe?

**Comment by benjohnde** [comment]
Sorry for the late answer, there seems to be a big in the DataMatrix Reader in the port. Can you provide an example code which works unter Android w/ xzing?
