### ISSUE TITLE
CRASH while setting up _capture.enableHeuristic() or _capture.invert = true

### ISSUE THREAD

**Issue by IVANKRUPSKI** [zxingify/zxingify-objc#500]
Am I doing something wrong?

I have downloaded example and I am constantly having crash if I
- set up _capture.enableHeuristic()
or if I set up
- _capture.invert = true

Real device: iPhon 11 and iPhone 6s+
iOS: 13.5.1

![image](https://user-images.githubusercontent.com/16180201/91669852-9339c280-eb18-11ea-8781-a410527bb04a.png)

**Comment by benjohnde** [comment]
This is a barely maintained ZXing port, I'd rather take a look at https://github.com/zxing-cpp/zxing-cpp created and maintained by the very ambitious @axxel!
