### ISSUE TITLE
Crashed on decode using ZXBinaryBitmap

### ISSUE THREAD

**Issue by akshardarji** [zxingify/zxingify-objc#502]
Hello @cwalcott,

we have tried with below functions to decode bitmap value:

```
func decodeQRResultFromImage(image: UIImage ,response: (_ success: Bool, _ result: String?, _ error: Error?) -> Void) {
        let barcodeImage = image.resizeWithWidth(width: 500)
        let compressData = barcodeImage == nil ? image.jpegData(compressionQuality: 0.5) : barcodeImage?.jpegData(compressionQuality: 0.5)
        let compressedImage = UIImage(data: compressData!)
        let source = ZXCGImageLuminanceSource(cgImage: compressedImage?.cgImage)
        let bitmap = ZXBinaryBitmap.binaryBitmap(with: ZXHybridBinarizer(source: source))
        let reader: ZXReader = ZXMultiFormatReader.reader() as! ZXReader
        do {
            let hints: ZXDecodeHints = ZXDecodeHints.init()
            hints.tryHarder = true
            let result = try reader.decode(bitmap as? ZXBinaryBitmap, hints: hints)
            response(true, result.text!, nil)
        } catch (let error) {
            response(false, nil, error)
        }
    }
```

As per our finding let me provide you steps:

1. Select QRImage from UIImagePickerController and passed on the above function. 
2. We got locked sometimes or sometimes success while doing things.

Note: Identified logs and detailed information by `Main Thread Checker` and `Address Sanitizer` Xcode Diagnostics. Details and logs are attaching here.

[ZXingCrashLogs.pdf](https://github.com/zxingify/zxingify-objc/files/5193413/ZXingCrashLogs.pdf)
<img width="617" alt="Screenshot 2020-09-08 at 11 47 05 PM" src="https://user-images.githubusercontent.com/14359160/92569741-9bbf9500-f29e-11ea-9550-4a72a829238f.png">

Kindly look into this as earliest.

Thanks

- SDK version: [5.2.3]
- Xcode version: [11.7]
- Your application language: [Swift-5]
- Cocoapods version: [Pod Version - 1.9.3]

**Comment by benjohnde** [comment]
Unfortunately, I can no longer provide support for this codebase, the topic will be closed. I recommend to take a look at https://github.com/zxing-cpp/zxing-cpp created and maintained by the very ambitious @axxel!
