### ISSUE TITLE
pod install fail

### ISSUE THREAD

**Issue by AlexanderPan** [zxingify/zxingify-objc#511]
```
[!] CocoaPods could not find compatible versions for pod "ZXingObjC":
  In Podfile:
    ZXingObjC (~> 3.6.7)

None of your spec sources contain a spec satisfying the dependency: `ZXingObjC (~> 3.6.7)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

**Comment by 4brunu** [comment]
This is because the last version published on cocoapods was `3.6.5`.
The version 3.6.6 and 3.6.7 are not published on cocoapods.
@benjohnde can you please help with this issue?
Thanks

**Comment by ykws** [comment]
@AlexanderPan Hi, if you need to install the latest version, the following `Podfile` install [the latest commit](https://github.com/zxingify/zxingify-objc/commit/e75eeff2089d66fc94514b43db3678a8812a9bbe) on the default branch, now installed 3.6.7.

```
  pod 'ZXingObjC', :git => 'https://github.com/zxingify/zxingify-objc'
```

**Comment by rbyyy** [comment]
who can fix the error? Now pod update is not convenient。

**Comment by benjohnde** [comment]
Should be fixed with current master!
