### ISSUE TITLE
The documentation reports that RSS-14 and RSS Expanded are supported for encoding

### ISSUE THREAD

**Issue by dehildum-paypal** [zxingify/zxingify-objc#512]
The read me lists the above bar codes are supported for writing/encoding. However, this is not the case. There is no code in the project to support encoding/writing these formats. The multi writer will throw an exception if these formats are selected.

**Comment by benjohnde** [comment]
This is a barely maintained ZXing port, I'd rather take a look at https://github.com/zxing-cpp/zxing-cpp created and maintained by the very ambitious @axxel!
