### ISSUE TITLE
The documentation reports that Maxicode is supported for encoding/writing

### ISSUE THREAD

**Issue by dehildum-paypal** [zxingify/zxingify-objc#513]
The documentation lists Maxicode as fully supported for reading and writing, but the multi writer will throw an exception if this format is selected. Checking the project show no code to support Maxicode encoding/writing.

**Comment by benjohnde** [comment]
This is a barely maintained ZXing port, I'd rather take a look at https://github.com/zxing-cpp/zxing-cpp created and maintained by the very ambitious @axxel!
