### ISSUE TITLE
Is there a way to decode CIQRCodeDescriptor using zxingify-objc

### ISSUE THREAD

**Issue by griffin-stewie** [zxingify/zxingify-objc#516]
I'm trying to decode QR code using CIQRCodeDescriptor's `errorCorrectedPayload`.

I was wondering to use decoder from zxingify-objc to do that. Is it possible?

I tried to use `ZXQRCodeDecodedBitStreamParser` but it is internal class.

Thank you.

**Comment by benjohnde** [comment]
Unfortunately, I can no longer provide support for this codebase, the topic will be closed. I recommend to take a look at https://github.com/zxing-cpp/zxing-cpp created and maintained by the very ambitious @axxel!
