### ISSUE TITLE
Is there a way to add the swift example to a React-Native project? Help needed.

### ISSUE THREAD

**Issue by eteamIH** [zxingify/zxingify-objc#521]
We are using react-native to scan GS1 Expanded barcodes using react-native-qrcode-scanner library which uses react-native-camera library for scanning barcodes.

It works perfectly on Android but doesn't scan GS1_Expanded barcodes on iPhone. I just tested the swift example with GS1_Expanded barcodes samples on iPhone 6 and it is working fine and I'd like to use this in my project. 

Can anyone please share how to integrate the example in my react-native project?

Thanks

**Comment by benjohnde** [comment]
Unfortunately I can't give support for other realms, the topic will be closed.
