### ISSUE TITLE
Camera delay on Iphone12 pro

### ISSUE THREAD

**Issue by sandy105** [zxingify/zxingify-objc#522]
I used this library to scan barcode , because I need to support RSS, but for other phone ,  it is ok , but only the iPhone 12 pro, the camera would delay, could someone help to check this?

**Comment by benjohnde** [comment]
Unfortunately, I can no longer provide support for this codebase, the topic will be closed. I recommend to take a look at https://github.com/zxing-cpp/zxing-cpp created and maintained by the very ambitious @axxel!
