### ISSUE TITLE
Generated duplicate UUIDs

### ISSUE THREAD

**Issue by suchettech** [zxingify/zxingify-objc#523]
I am getting following warnings while building ZXingObjC

following is log of pod install, can someone help me regarding this, Thanks!!

Updating local specs repositories
Analyzing dependencies
Pre-downloading: `ZXingObjC` from `https://github.com/zxingify/zxingify-objc.git`
Downloading dependencies
Installing ZXingObjC (3.6.5)
Generating Pods project
Prebuild frameworks (total 1)
Prebuilding ZXingObjC...

[!] [Xcodeproj] Generated duplicate UUIDs:

**Comment by benjohnde** [comment]
Hopefully this is fixed with current master!
