### ISSUE TITLE
Getting warning on this line while running on Xcode 13

### ISSUE THREAD

**Issue by sanjay-mohnani-rakuten** [zxingify/zxingify-objc#546]
https://github.com/zxingify/zxingify-objc/blob/e75eeff2089d66fc94514b43db3678a8812a9bbe/ZXingObjC/datamatrix/decoder/ZXDataMatrixDecodedBitStreamParser.m#L246

<pre ccp_infra_version="3" ccp_infra_timestamp="1633406274620" ccp_infra_user_hash="692652827" ccp_infra_copy_id="" data-ccp-timestamp="1633406274620" style="font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);">

We are getting below mentioned warning when we run this pod on Xcode 13 -

/Users/xxxx-xxxx/Source/card-ios/Pods/ZXingObjC/ZXingObjC/datamatrix/decoder/ZXDataMatrixDecodedBitStreamParser.m:224:57: Expression does not compute the number of elements in this array; element type is 'const unichar' (aka 'const unsigned short'), not 'char'

 Is it safe to proceed with the above warning or not?

</pre>

**Comment by benjohnde** [comment]
Should be fixed with current master!
