### ISSUE TITLE
 Error installing ZXingObjC

### ISSUE THREAD

**Issue by dexkode4** [zxingify/zxingify-objc#547]
Hi please , I get this error when running pod install

[!] Error installing ZXingObjC
[!] /usr/local/bin/git clone https://github.com/zxingify/zxingify-objc.git /var/folders/yy/gfwzsmjd0hqd0mgl8bz7wm1c0000gn/T/d20211019-79043-1xmlp3x --template= --single-branch --depth 1 --branch 3.6.5

Cloning into '/var/folders/yy/gfwzsmjd0hqd0mgl8bz7wm1c0000gn/T/d20211019-79043-1xmlp3x'...
error: 7604 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

My configuration 

> System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 20.82 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ~0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:

**Comment by benjohnde** [comment]
Should be fixed with current master!
