### ISSUE TITLE
bar code scanner scans QR

### ISSUE THREAD

**Issue by stdio137** [zxingify/zxingify-objc#567]
I have used this library
While integrating I have Initiated the Bar code scan and also provided the hints for bar code scan

    // add hints for bar code scanning
    [self.capture.hints addPossibleFormat:kBarcodeFormatUPCA];
    [self.capture.hints addPossibleFormat:kBarcodeFormatUPCE];
    [self.capture.hints addPossibleFormat:kBarcodeFormatEan13];
    [self.capture.hints addPossibleFormat:kBarcodeFormatEan8];
    [self.capture.hints addPossibleFormat:kBarcodeFormatCodabar];
    [self.capture.hints addPossibleFormat:kBarcodeFormatCode39];
    [self.capture.hints addPossibleFormat:kBarcodeFormatCode93];
    [self.capture.hints addPossibleFormat:kBarcodeFormatCode128];
    [self.capture.hints addPossibleFormat:kBarcodeFormatITF];
    [self.capture.hints addPossibleFormat:kBarcodeFormatRSS14];
    [self.capture.hints addPossibleFormat:kBarcodeFormatRSSExpanded];
but I put the camera in front of QR code it scans and returns me some dummy value in the following method:

(void)captureResult:(ZXCapture *)capture result:(ZXResult *)result
in result I am getting some unwanted value as 113244

**Comment by stdio137** [comment]
Can you please have a look to this issue?

**Comment by benjohnde** [comment]
Unfortunately, I can no longer provide support for this codebase, the topic will be closed. I recommend to take a look at https://github.com/zxing-cpp/zxing-cpp created and maintained by the very ambitious @axxel!
