### ISSUE TITLE
Maxicode missing encoder folder despite stating it's supported in readme

### ISSUE THREAD

**Issue by OrbitMan92** [zxingify/zxingify-objc#572]
Not sure if the documentation is incorrect or if the encoder folder is missing - but either way maxi code encoding is not supported, hopefully will be added soon!

**Comment by benjohnde** [comment]
Unfortunately, I can no longer provide support for this codebase, the topic will be closed. I recommend to take a look at https://github.com/zxing-cpp/zxing-cpp created and maintained by the very ambitious @axxel!
