### ISSUE TITLE
Not recognized by adobe QR-generator

### ISSUE THREAD

**Issue by JJIKKYU** [zxingify/zxingify-objc#573]
https://express.adobe.com/ko-KR/tools/qr-code-generator

The QR code generated from the link above is not recognized.
The iPhone basic camera is recognized, but why does this only happen in Zxing?

Please check why it is not recognized.

**Comment by benjohnde** [comment]
Unfortunately, I can no longer provide support for this codebase, the topic will be closed. I recommend to take a look at https://github.com/zxing-cpp/zxing-cpp created and maintained by the very ambitious @axxel!
