### ISSUE TITLE
Hope there is a new version update that doesn't throw a crash when the barcode is malformed, but a callback

### ISSUE THREAD

**Issue by tc976562936** [zxingify/zxingify-objc#574]
Terminating app due to uncaught exception 'IllegalArgumentException', reason: 'Requested contents should be 7 or 8 digits long, but got 3'
terminating with uncaught exception of type NSException

**Comment by benjohnde** [comment]
Unfortunately, I can no longer provide support for this codebase, the topic will be closed. I recommend to take a look at https://github.com/zxing-cpp/zxing-cpp created and maintained by the very ambitious @axxel!
