### ISSUE TITLE
Publish 3.6.7

### ISSUE THREAD

**Issue by gr347wh173n0r7h** [zxingify/zxingify-objc#577]
Looks like the latest version in [Cocaopods](https://github.com/CocoaPods/Specs/blob/master/Specs/f/3/c/ZXingObjC/3.6.5/ZXingObjC.podspec.json) is `3.6.5`, can we get `3.6.7` published?

**Comment by adil-hussain-84** [comment]
Chasing this up. Is there a reason why version 3.6.7 has not been published to CocoaPods?

**Comment by khanakia** [comment]
is there any update on the new version 3.6.7

**Comment by adil-hussain-84** [comment]
Version 3.6.8 was released yesterday thanks to @benjohnde. This issue can be closed.
