### ISSUE TITLE
iOS17 Error：COEFFICIENTS MUST HAVE AT LEAST ONE ELEMENT

### ISSUE THREAD

**Issue by blooming2017** [zxingify/zxingify-objc#578]
ViewController报错.COEFFICIENTS MUST HAVE AT LEAST ONE ELEMENT

堆栈信息如下：
CoreFoundation                      0x00000001a38065ec CEB74A0C-5EA4-3F5A-9DE8-73F0DAD2F4CB + 972268
libobjc.A.dylib                     0x000000019bb1fc00 objc_exception_throw + 60
0x0000000106761a90 _Z25GFrameBufferObjectDeleterPNSt3__18multimapINS_4pairIiiEEP18GFrameBufferObjectNS_4lessIS2_E

**Comment by benjohnde** [comment]
Unfortunately, I can no longer provide support for this codebase, the topic will be closed. I recommend to take a look at https://github.com/zxing-cpp/zxing-cpp created and maintained by the very ambitious @axxel!
